#=========== server ===========
server:
  port: 8121
  address: localhost
# ========== postgres ==========
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/flow-note
    username: zhangqingfeng
    password: 12345678
  # ========== Redis ==========
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0
      timeout: 2000ms


